### ISSUE TITLE
Single Particle Detection Troubleshooting: "Error using vertcat"

### ISSUE THREAD

**Issue by leti332** [DanuserLab/u-track#5] opened 2020-01-15 00:02 UTC
It seems like I'm running into issues with particle detection. 

My system specifications are the following:
Matlab version: 9.2.0.556344 (R2017a)
Operating System: Mac OS X Version: 10.15.2 Build: 19C57
Java VM Version: Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-But Server VM mixed mode

The main error that comes up after running through the detection and tracking steps is "Error using vertcat. Dimensions of matrices being concatenated are not consistent." Any help on this issue would be greatly appreciated!

**Comment by DanuserLab** [comment] 2024-10-24 20:16
Sorry for the delayed reply. We were unable to reproduce the error on our end. If you're still encountering the issue, please send us the full error message and a sample dataset so we can investigate further.

For now, I'll go ahead and close this issue. Feel free to reopen it or create a new issue if you need further assistance.

**Closed as completed by DanuserLab** 2024-10-24 20:16 UTC
