### ISSUE TITLE
Error occurs when calling plotCompTrack / Can not open result movies

### ISSUE THREAD

**Issue by yiqiz2** [DanuserLab/u-track#13] opened 2023-03-24 20:03 UTC
I used the `MovieSelectorGUI` for analysis. As I tried to follow the visualization instructions and call the function `plotCompTrack`, an error occurred and gave me the following message:

> Error using inputParserRetrofit/parse (line 190)
> The value of 'trackedFeatureInfo' is invalid. It must satisfy the function: @(s)isstruct(s)||isnumeric(s).
> 
> Error in inputParserRetrofit/subsref (line 116)
>                 [varargout{1:nargout}] = builtin('subsref',obj,S);
> 
> Error in plotCompTrack (line 82)
> ip.parse(trackedFeatureInfo, varargin{:});

Is there anyone could bring me some insights on this?

At the same time, I also noticed that I was unable to open the .mov movie generated by the function. Is there anyone know what might be the cause of this?

**Comment by DanuserLab** [comment] 2024-05-17 16:48
Thank you for reaching out and providing detailed information about the issue you're encountering.

For the error with the plotCompTrack function, we were unable to reproduce this problem on our end. Could you please double-check the inputs you're providing to the plotCompTrack function and ensure they meet the expected format? As well check the output of your scriptTrackGeneral.

Regarding the issue with opening the .mov files, this problem arises from changes in internal functions starting from Matlab version 2021a. If you are using Matlab 2021a or later, the generated .mov files might not open correctly. We are currently working on a fix for this. In the meantime, we recommend using the .avi option in our viewer GUI, which works without any issues.

Thank you for your understanding and patience. If you have any further questions or need additional assistance, please don't hesitate to ask.

**Closed as completed** 2024-10-24 20:06 UTC
